### ISSUE TITLE
how to add PackRTree info to outputStream?

### ISSUE THREAD

**Issue by sendreams** [flatgeobuf/flatgeobuf#372] opened 2024-06-26 15:20 UTC
`public class FeatureCollectionConversions {
    public static void serialize(
            SimpleFeatureCollection featureCollection,
            long featuresCount,
            OutputStream outputStream)
            throws IOException {
        SimpleFeatureType featureType = featureCollection.getSchema();
        FlatBufferBuilder builder = FlatBuffers.newBuilder(16 * 1024);
        try {
            HeaderMeta headerMeta = HeaderMetaUtil.fromFeatureType(featureType, featuresCount);
            outputStream.write(Constants.MAGIC_BYTES);
            HeaderMeta.write(headerMeta, outputStream, builder);
            builder.clear();
            try (FeatureIterator<SimpleFeature> iterator = featureCollection.features()) {
                while (iterator.hasNext()) {
                    SimpleFeature feature = iterator.next();
                    FeatureConversions.serialize(feature, headerMeta, outputStream, builder);
                    builder.clear();
                }
            }
        } finally {
            FlatBuffers.release(builder);
        }
    }
}`

I used GeoTools to generate FlatGeobuf files. This method does not handle PackRTree information when creating the FGB file, resulting in the inability to perform deserialize queries. My question is, where is the PackRTree information stored in the output file? Is it after the header metadata, or at the beginning or end of the entire file? Could you provide me with some pseudocode hints?

**Comment by sendreams** [comment] 2024-06-26 15:22
```java code
public static void serialize(
            SimpleFeatureCollection featureCollection,
            long featuresCount,
            OutputStream outputStream)
            throws IOException {
        SimpleFeatureType featureType = featureCollection.getSchema();
        FlatBufferBuilder builder = FlatBuffers.newBuilder(16 * 1024);
        try {
            HeaderMeta headerMeta = HeaderMetaUtil.fromFeatureType(featureType, featuresCount);
            outputStream.write(Constants.MAGIC_BYTES);
            HeaderMeta.write(headerMeta, outputStream, builder);
            builder.clear();
            try (FeatureIterator<SimpleFeature> iterator = featureCollection.features()) {
                while (iterator.hasNext()) {
                    SimpleFeature feature = iterator.next();
                    FeatureConversions.serialize(feature, headerMeta, outputStream, builder);
                    builder.clear();
                }
            }
        } finally {
            FlatBuffers.release(builder);
        }
    }

**Comment by sendreams** [comment] 2024-06-26 15:30
I also reported this on GeoTools' Jira, but their response has been too slow. Some issues have not been addressed for over a month, and my work can't wait any longer. I have to try to solve it myself, but this problem is indeed quite tricky.

**Comment by sendreams** [comment] 2024-06-26 15:55
@bjornharrtell Of course, I know that. It's just that I've been waiting for over a month on the GeoTools forum without any response. I suddenly thought of asking here because I don't have much time to wait any longer. I just need a possible solution. As it stands, I might have to consider other options.
Thank you for your response.

**Comment by sendreams** [comment] 2024-06-26 16:02
I have another question. I see that the PackRTree and NodeItem classes are already present in the Java code. Doesn't this mean it has been implemented? I am guessing that the feature information needs to be converted to PackRTree and then written to the outputStream. I found an image indicating that the PackRTree information should be placed after the headermeta and before the feature records.

**Comment by sendreams** [comment] 2024-06-26 16:03
![image](https://github.com/flatgeobuf/flatgeobuf/assets/4160051/8b7b6088-8779-4cd1-97cc-4a87aff8df5d)

**Comment by bjornharrtell** [comment] 2024-06-26 16:18
@sendreams yes it does appear that I ported the parts to write the spatial index to PackedRTree.java and even with some basic testcase at https://github.com/flatgeobuf/flatgeobuf/blob/master/src/java/src/test/java/org/wololo/flatgeobuf/PackedRTreeTest.java#L73.

So what is missing is actually "just" using it when assembling the full outputfile in GeoTools, if I rememer correctly. And some option to control it in GeoTools, since it's not relevant when using FlatGeobuf as output format in GeoTools/GeoServer WFS which is why I contributed to GeoTools in the first place.

And yes, the serialized spatial index tree is expected to be after the header and before feature data. The presence of spatial index is indicated in the header.

**Comment by bjornharrtell** [comment] 2024-06-26 16:24
@sendreams be aware that for spatial indexing to work, the features must be sorted using the hilbert order and written in that order. This can be an issue if data is large and doesn't fit into memory. That has been solved as implemented in for example GDAL by writing sorted set to disk on the fly before calculcating the spatial index then rewrite.

**Comment by sendreams** [comment] 2024-06-27 02:48
@bjornharrtell 
```java
public static int calcSerializeSize(SimpleFeature feature, HeaderMeta headerMeta)
            throws IOException {

        FlatBufferBuilder builder = FlatBuffers.newBuilder(16 * 1024);
        final int propertiesOffset = createProperiesVector(feature, builder, headerMeta);
        org.locationtech.jts.geom.Geometry geometry =
                (org.locationtech.jts.geom.Geometry) feature.getDefaultGeometry();
        final int geometryOffset =
                geometry == null
                        ? 0
                        : GeometryConversions.serialize(builder, geometry, headerMeta.geometryType);
        return Feature.createFeature(builder, geometryOffset, propertiesOffset, 0);
    }
```

i have modified the source code of FeatureConversions and added the calcSerializeSize method to calculate the write size of a feature.

**Comment by bjornharrtell** [comment] 2024-06-27 11:59
@sendreams looks more or less correct but might be some minor detail missing that needs to be debugged, and unfortunately that is something that I don't seem to have time for in the near future. If you can prepare this with test case reproduction of the error in GeoTools as a proper pull request (draft) to that project it would likely help progress though.

**Comment by bjornharrtell** [comment] 2024-06-27 12:10
I'm closing this because this cannot be implemented here due to that feature representation is outside the scope of the FlatGeobuf Java reference implementation. It needs to be implemented in GeoTools. Relevant issue in GeoTools is https://osgeo-org.atlassian.net/browse/GEOT-7609.

**Closed by bjornharrtell** 2024-06-27 12:10 UTC

**Comment by sendreams** [comment] 2024-06-28 00:33
@bjornharrtell thanks
