### ISSUE TITLE
Error (panicked) at FgbReader::open when reading an EPSG:25832 fgb file

### ISSUE THREAD

**Issue by tumluliu** [flatgeobuf/flatgeobuf#167] opened 2022-01-03 11:12 UTC
Hi there, thank you for making such a great lib! I'm pretty new to both rust and flatgeobuf, and facing an issue when opening a fgb dataset with CRS EPSG:25832. It complains with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Geometry("Utf8 error for string in 196..1969: invalid utf-8 sequence of 1 bytes from index 1542\n\twhile verifying table field `wkt` at position 188\n\twhile verifying table field `crs` at position 60\n")'
```

The dataset is a subset of Bavaria cycling network from https://www.ldbv.bayern.de/produkte/weitere/opendata.html , selected and exported to fgb format with QGIS. I am able to open it in QGIS, but met the above issue when reading it with flatgeobuf lib. For other dataset with EPSG:4326 system, there is no such problem. But I am not sure if the CRS is the reason. Could you help shed some light? Thanks a lot! For some reason, I could not upload the sample dataset here. sorry about that!

**Comment by bjornharrtell** [comment] 2022-01-03 12:58
Thanks for your interest @tumluliu, this does seem unexpected and I will try to get to the bottom if it. Likely need help from Rust maintainer @pka though.

**Comment by pka** [comment] 2022-01-03 21:38
Hi @tumluliu

I've converted the Shapfile to FGB with GDAL 3.4.0:
```
ogr2ogr -f FlatGeobuf Radweg_gesamt.fgb  Radweg_gesamt.shp
```

ogrinfo -al -so Radweg_gesamt.fgb
```
INFO: Open of `Radweg_gesamt.fgb'
      using driver `FlatGeobuf' successful.

Layer name: Radweg_gesamt
Geometry: Line String
Feature Count: 34974
Extent: (495737.725000, 5238334.501000) - (871457.835000, 5604729.181000)
Layer SRS WKT:
PROJCRS["ETRS89 / UTM zone 32N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - 6°E to 12°E and ETRS89 by country"],
        BBOX[38.76,6,83.92,12]],
    ID["EPSG",25832]]
Data axis to CRS axis mapping: 1,2
FGN: String (254.0)
FKN: String (20.0)
FTY: String (20.0)
LANDKREIS: String (50.0)
STAND: String (15.0)
```

The degree symbol in the SRS looks suspicious!

vim Radweg_gesamt.fgb shows:
```
AREA["Europe - 6Â°E to 12Â°E and ETRS89 by country"]
```
@bjornharrtell: A non-UTF8 SRS would be against the spec, right?

But the following test passes:
```
    let mut filein = BufReader::new(File::open("../../test/data/Radweg_gesamt.fgb")?);
    let mut fgb = FgbReader::open(&mut filein)?;
    let count = fgb.select_all()?;
    assert_eq!(count, 34974);

    let feature = fgb.next()?.unwrap();
    assert_eq!(feature.property("FTY"), Some("Radweg".to_string()));

    assert_eq!(fgb.header().crs().unwrap().code(), 25832);
    assert_eq!(
        fgb.header().crs().unwrap().wkt(),
        Some(
            r#"PROJCRS["ETRS89 / UTM zone 32N",BASEGEOGCRS["ETRS89",DATUM["European Terrestrial Reference System 1989",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4258]],CONVERSION["UTM zone 32N",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",9,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",0.9996,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",500000,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1]],USAGE[SCOPE["unknown"],AREA["Europe - 6°E to 12°E and ETRS89 by country"],BBOX[38.76,6,83.92,12]],ID["EPSG",25832]]"#
        )
    );
```

How did you get the panic?

**Comment by pka** [comment] 2022-01-03 21:58
Made a minimal excerpt near Switzerland :switzerland::
```
ogr2ogr -where "FKN='005910'" -f FlatGeobuf Radweg_ETRS89.fgb Radweg_gesamt.shp
```

[Radweg_ETRS89.zip](https://github.com/flatgeobuf/flatgeobuf/files/7804203/Radweg_ETRS89.zip)


Can you reproduce the panic with that file?

**Comment by tumluliu** [comment] 2022-01-03 22:03
Hi @pka , thank you for your digging and the very detailed info! The degree symbol looks like the cause indeed. I will try with the file you created right now

**Comment by tumluliu** [comment] 2022-01-03 22:26
@pka some results from my quick tests:

1. my program doesn't panic with your test dataset `Radweg_ETRS89.fgb`
2. it still panic with the subset I created with qgis for Munich area at the line `let mut fgb = FgbReader::open(&mut filein).unwrap();`

I also checked my file with your ogrinfo command, and got this:

```
INFO: Open of `munich_radweg.fgb'
      using driver `FlatGeobuf' successful.

Layer name: munich_radweg
Geometry: Multi Line String
Feature Count: 1268
Extent: (652486.937000, 5310799.318000) - (712816.382000, 5350043.924000)
Layer SRS WKT:
PROJCRS["ETRS89 / UTM zone 32N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - 6°E to 12°E and ETRS89 by country"],
        BBOX[38.76,6,83.92,12]],
    ID["EPSG",25832]]
Data axis to CRS axis mapping: 1,2
FGN: String (254.0)
FKN: String (20.0)
FTY: String (20.0)
LANDKREIS: String (50.0)
STAND: String (15.0)
```

3. I'm trying to convert the subset of Munich from shp to fgb and test it again, but may report the result tomorrow

**Comment by tumluliu** [comment] 2022-01-03 22:37
okay, I got the result as well for 3: it doesn't panic for the dataset converted with ogr2ogr from shp. 

I also compared the two fgb data files' ogrinfo, and found there is only one difference which is Geometry type:

```
❯ diff munich_radweg.fgb.info munich_radweg_ogr.fgb.info
1c1
< INFO: Open of `munich_radweg.fgb'
---
> INFO: Open of `munich_radweg_ogr.fgb'
5c5
< Geometry: Multi Line String
---
> Geometry: Line String
```

The problematic one generated with QGIS has the `Multi Line String` geometry type. Could this be the reason?

**Comment by bjornharrtell** [comment] 2022-01-04 01:54
Still rather confusing, not sure what to make of it.

The crs string encoding is also strange but unsure if related.

**Comment by pka** [comment] 2022-01-04 07:08
Which GDAL version does QGIS use (Help -> About -> About) and which version do you have on the command line (`ogrinfo --version`)? On which OS are you? If you create the minimal excerpt yourself, is it working, too?

**Comment by tumluliu** [comment] 2022-01-04 10:09
thanks for the further hints! @pka 

> Which GDAL version does QGIS use (Help -> About -> About) 
I'm using qgis 3.20 whose bundled gdal is **3.3.0**

> which version do you have on the command line (`ogrinfo --version`)? 
my gdal from cmd is **3.4.0**

> On which OS are you? 
qgis is on windows; 
gdal cmd and the rust test codes are from ubuntu 20.04

> If you create the minimal excerpt yourself, is it working, too?
yes, it worked with no panic

I'm searching if there is any relevant known issue in gdal 3.3.0 when converting to flatgeobuf...

**Comment by bjornharrtell** [comment] 2022-01-04 18:33
So I think the underlying cause is https://github.com/OSGeo/gdal/issues/5060.

**Comment by bjornharrtell** [comment] 2022-01-04 18:37
@pka since we have instances of this in the wild and likely other reader implementations isn't that sensitive about it.. can the rust code be persuaded to give up and treat invalid utf-8 as null or empty in this case?

**Comment by pka** [comment] 2022-01-05 20:57
As I understand, the UTF-8 check is done as part of the flatbuffers verification. I can't find a flag to turn this check off, so an option for disabling verification would be needed. I'm hesitating adding this and would prefer telling people how to fix their FGB file. I could return a better message for that.

**Comment by bjornharrtell** [comment] 2022-01-05 21:16
@pka I think it would at least make sense to be able to turn off verification, it can also be a performance thing for cases where your data is trusted.

Anyway, https://github.com/OSGeo/gdal/issues/5060 is now fixed (hopefully) but it will likely take a long time before it reaches users unfortunately.

**Comment by pka** [comment] 2022-02-23 20:11
With b6c975c03f0b2e51a767ef578a361a5ada6d41ce there is now a method `open_unchecked` which skips FlatBuffers verfication.

**Closed by pka** 2022-02-23 20:11 UTC
